global using API;
global using API.AppServices;
global using API.Filters;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using TokenOptions = Core.Jwt.TokenOptions;
global using Role = Domain.Entities.Role;
global using User = Domain.Entities.User;
global using Core.Encryption;
global using Microsoft.OpenApi.Models;
global using Microsoft.AspNetCore.Identity;
global using Core.Utilities.Results;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Infrastructure;
global using Services;
global using Domain.Entities;
global using StackExchange.Redis;
global using Serilog;
global using Microsoft.Extensions.FileProviders;